- type: clash
  options:
    url: https://fq.lonxin.net/clash/proxies

- type: clash
  options:
    url: https://sspool.herokuapp.com/clash/proxies

- type: clash
  options:
    url: https://proxypool.fly.dev/clash/proxies

- type: clash
  options:
    url: https://sspool.nl/clash/proxies


